# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

#platform :ios, "8.0"
#use_frameworks!

platform :ios, '7.0'

pod 'ReactiveCocoa', '2.1.8'

target 'RWReactivePlayground' do

end

target 'RWReactivePlaygroundTests' do

end

